### PR TITLE
Create a bundle or image directly as a tar file

### PR DESCRIPTION
**Pull request by DennisDenuto**
Attempts to implement: https://github.com/vmware-tanzu/carvel-imgpkg/issues/55

TODO:

- [x] manual test spike and ensure it works writing to a tarball directly not requiring a registry
- [x] look into providing a registry that can serve local images and images from the registry as an alternate way to implement this story
- [x] throw spike away and TDD implementation
- [x] consider whether a new command is needed "build" or whether this is part of the "push" command

Authored-by: Dennis Leon <leonde@vmware.com>

### CODE REVIEW

**Comment by pivotaljohn** [comment]
FWIW, there _may_ be an additional use-case for this feature: vmware-tanzu/carvel-kbld#158.

`kbld` has a mode where it does not push built artifacts. Having the ability to do so with `imgpkg` bundles fits nicely with that mode.

**Comment by cppforlife** [comment]
we'll try to rework based on https://github.com/vmware-tanzu/carvel-imgpkg/issues/55#issuecomment-962209740

**Comment by cppforlife** [comment]
per discussion with dennis, will close. not sure if above proposed solution will result in some code reuse from this PR.

**Comment by parteekcoder** [comment]
@cppforlife I want to work on `Package Repository to tar` this project but does not know where can i start from. I saw this PR which relates to this project.

Could you please help me

**Pull request closed without merging**
