### PR TITLE
Use correct `vmware-tanzu/carvel-imgpkg` module name instead of `k14s`

### LINKED ISSUE #278: Cannot use `go get` to include imgpkg libraries
**What steps did you take:**
In a new go project:
```
❯ go mod init example.com
go: creating new go.mod: module example.com

❯ go get github.com/vmware-tanzu/carvel-imgpkg
go get: github.com/vmware-tanzu/carvel-imgpkg@v0.20.0: parsing go.mod:
	module declares its path as: github.com/k14s/imgpkg
	        but was required as: github.com/vmware-tanzu/carvel-imgpkg
```

I want to use the carvel libraries in a go project, but I am unable to use `go get` to pull in that dependency

**What happened:**
The `go.mod` should declare it's module as `github.com/vmware-tanzu/carvel-imgpkg` not `github.com/k14s/imgpkg`

**What did you expect:**
Be able to pull in the carvel libraries

**Anything else you would like to add:**
N/a

**Environment:**

Go 1.17 env:
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/ubuntu/.asdf/installs/golang/1.17.2/go/bin"
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ubuntu/.asdf/installs/golang/1.17.2/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/.asdf/installs/golang/1.17.2/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/ubuntu/.asdf/installs/golang/1.17.2/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/ubuntu/.asdf/installs/golang/1.17.2/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ubuntu/workspace/test-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2207886280=/tmp/go-build -gno-record-gcc-switches"
```

- imgpkg version (use `imgpkg --version`): N/a
- Docker registry used (e.g. `Docker HUB`): N/a
- OS (e.g. from `/etc/os-release`): N/a

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by jpmcb**
This PR changes references of the `k14s/imgpkg` go module to be `vmware-tanzu/carvel-imgpkg`, primarily in the `go.mod` file. This is required to be able to run
```
go get github.com/vmware-tanzu/carvel-imgpkg
```
without errors

Ran `./hack/build-and-lint.sh` to verify

Fixes #278

### CODE REVIEW

**Comment by pivotaljohn** [comment]
Thanks for chopping wood, here, @jpmcb.

Gonna mark this as "draft" only to avoid accidentally merging this before we're ready.

Please see [comment on #278](https://github.com/vmware-tanzu/carvel-imgpkg/issues/278#issuecomment-945944381).

**Comment by DennisDenuto** [comment]
Thanks for the PR! 🚀  @jpmcb 

In order to make this change consistent with other tools in the carvel suite,  can you please create a `docs/dev.md` file with a section documenting the module rename. It is hopefully one way to help inform folk of this rename - if they run into issues. 

For more details refer to the "documentation" section: https://github.com/vmware-tanzu/carvel/issues/153

**Comment by pivotaljohn** [comment]
With those docs in place, we'd be good to just roll forward: pulling out of draft. 👍🏻

**Comment by DennisDenuto** [comment]
@joaopapereira mentioned at standup he would prefer this PR go in a release without any other changes.

So, that is looking to be v0.22.0.

**Comment by jpmcb** [comment]
@DennisDenuto - added a `docs/dev.md` - let me know if there are any other changes y'all want!

**Comment by DennisDenuto** [comment]
Thanks @jpmcb `docs/dev.md` look great!! 

We plan on having this PR merged/released for `v0.22.0`

**Pull request merged**
