### PR TITLE
Add ability to set labels on image push

### LINKED ISSUE #153: Add annotations/labels to bundle
**Describe the problem/challenge you have**
OCI images would be a great place to store machine learning models. ImgPkg works as expected with storing a generic model file, however there are times in which you may want to select between different model versions based on metadata such as the training score or dataset used. 

**Describe the solution you'd like**
I would like to add basic metadata to bundles to help select them. Looking for similar functionality to https://docs.docker.com/engine/reference/builder/#label or https://github.com/opencontainers/image-spec/blob/master/annotations.md. Would be nice to also have a way to search or filter them when looking through the repository. 

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by old-ocean-creature**
Add ability to set labels on image push

### CODE REVIEW

**Comment by old-ocean-creature** [comment]
fixes https://github.com/vmware-tanzu/carvel-imgpkg/issues/153

**Review by joaopapereira — CHANGES_REQUESTED** [review]
Hey
Thanks for putting together this PR.
Looks like some tests are failing, do you mind taking a look to see what is happening.

Also not sure if it would make more sense for it to be called `--label`  singular since you would have to provide the `--label` flag per label you want to add.
Another nice to have is for this to be provided with the ability to add labels to the bundles as well.
And to top it off, if you could also add some tests to ensure that the labels are being added correctly that would be awesome.

Let me know if you need help with any of the above comments

**Comment by phenixblue** [comment]
@joaopapereira I believe this can be closed now since #552 was merged

**Comment by joaopapereira** [comment]
Closing since the work was already done

**Pull request closed without merging**
