### PR TITLE
Revert "Bump go version to 1.21.3"

### PR DESCRIPTION
**Pull request by sethiyash**
Reverts carvel-dev/imgpkg#602

### CODE REVIEW

**Comment by praveenrewar** [comment]
I am a bit curious as the PR says `Revert "Bump go version to 1.21.3 in v0.38.x line"`, but it's actually on develop 🤔

**Comment by sethiyash** [comment]
> I am a bit curious as the PR says Revert "Bump go version to 1.21.3 in v0.38.x line", but it's actually on develop 🤔

I accidentally raised and merged this pull request on develop branch instead of v0.38.x. Consequently, there are now two commits for the Go version bump to 1.20.3 in the develop branch. I'm considering reverting this change.

**Comment by joaopapereira** [comment]
This PR has no changes

**Comment by joaopapereira** [comment]
Do we still need this?

**Comment by praveenrewar** [comment]
Closing it as there are no changes in this PR.

**Pull request closed without merging**
